print("Apresente 5 itens da sua lista de compras")
a = input ("\nDigite o Item 1: ")
b = input ("Digite o Item 2: ")
c = input ("Digite o Item 3: ")
d = input ("Digite o Item 4: ")
e = input ("Digite o Item 5: ")


print("\n")
num1 = input("Digite a quantidade do item 1: ")
num2 = input('Digite a quantidade do item 2: ')
num3 = input('Digite a quantidade do item 3: ')
num4 = input('Digite a quantidade do item 4: ')
num5 = input('Digite a quantidade do item 5: ')

print("\nLista de Compras")
print(num1, "-",a)
print(num2, "-",b)
print(num3, "-",c)
print(num4, "-",d)
print(num5, "-",e)
